const CATEGORIES=[['🍔','Comida'],['🚗','Transporte'],['🛒','Compras'],['🏠','Hogar'],['💊','Salud'],['🎮','Ocio'],['💳','Servicios'],['📦','Otros']];
const PAYMENTS=['💵 Efectivo','💳 Débito','💳 Crédito','🏦 Transferencia','❓ Otro'];
const KEY='mis_gastos_v5';const SETTINGS_KEY='mis_gastos_settings_v5';const OLD_KEY='mis_gastos_v3';const OLD_SETTINGS='mis_gastos_settings_v3';
let expenses=JSON.parse(localStorage.getItem(KEY)||'null');
let settings=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'null');
let commitments=JSON.parse(localStorage.getItem('mis_gastos_commitments_v5')||'[]');
if(!expenses){expenses=JSON.parse(localStorage.getItem(OLD_KEY)||'[]');localStorage.setItem(KEY,JSON.stringify(expenses))}
if(!settings){settings=JSON.parse(localStorage.getItem(OLD_SETTINGS)||'{"budget":0}');localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}
let quickCategory='';let commitmentTab='active';let selectedPeriod=localStorage.getItem('mis_gastos_v51_selected_period')||today().slice(0,7);
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n)||0),today=()=>new Date().toISOString().slice(0,10),monthKey=d=>String(d).slice(0,7),currentMonth=()=>selectedPeriod,catIcon=n=>(CATEGORIES.find(x=>x[1]===n)||['📦'])[0];
const save=()=>localStorage.setItem(KEY,JSON.stringify(expenses)),saveSettings=()=>localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings)),saveCommitments=()=>localStorage.setItem('mis_gastos_commitments_v5',JSON.stringify(commitments));
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function dateObj(s){const [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d)}
function monthDiff(a,b){return (b.getFullYear()-a.getFullYear())*12+b.getMonth()-a.getMonth()}
function installmentInfo(c,month=currentMonth()){
 const start=dateObj(c.startDate), target=dateObj(month+'-01');let elapsed=monthDiff(start,new Date(target.getFullYear(),target.getMonth(),1));
 const pausedMonths=Number(c.pausedMonths)||0; elapsed-=pausedMonths;
 const current=elapsed+1;const total=Number(c.totalInstallments)||1;return {current,remaining:Math.max(0,total-current),total,active:current>=1&&current<=total,completed:current>total}
}
function fixedActive(c,month=currentMonth()){return c.status==='active'&&monthKey(c.startDate)<=month}
function commitmentForMonth(c,month=currentMonth()){
 if(c.type==='fixed') return c.status==='active'&&monthKey(c.startDate)<=month?Number(c.amount):0;
 const info=installmentInfo(c,month);return c.status==='active'&&info.active?Number(c.amount):0;
}
function activeCommitments(month=currentMonth()){return commitments.filter(c=>c.status==='active'&& (c.type==='fixed'?fixedActive(c,month):installmentInfo(c,month).active))}
function commitmentState(c,month=currentMonth()){if(c.status==='paused'||c.status==='cancelled')return c.status;if(c.type==='installment'){const i=installmentInfo(c,month);if(i.completed)return 'completed'}return c.status}
function commitmentLabel(c,month=currentMonth()){if(c.type==='fixed')return '🔄 Gasto fijo mensual';const i=installmentInfo(c,month);return `💳 Cuota ${Math.min(Math.max(i.current,1),i.total)} de ${i.total}`}
function commitmentTotal(month=currentMonth()){return activeCommitments(month).reduce((s,c)=>s+commitmentForMonth(c,month),0)}
function populate(){
 $('categoryGrid').innerHTML=CATEGORIES.map(([i,n])=>`<button type="button" class="category-choice" data-cat="${n}"><span>${i}</span><small>${n}</small></button>`).join('');
 $('quickCategories').innerHTML=CATEGORIES.map(([i,n])=>`<button type="button" class="quick-cat" data-qcat="${n}"><span>${i}</span><small>${n}</small></button>`).join('');
 $('paymentGrid').innerHTML=PAYMENTS.map(x=>`<button type="button" class="payment-choice" data-pay="${x}">${x}</button>`).join('');
 $('categoryFilter').innerHTML='<option value="">Todas las categorías</option>'+CATEGORIES.map(([i,n])=>`<option value="${n}">${i} ${n}</option>`).join('');
 $('commitmentCategory').innerHTML=CATEGORIES.map(([i,n])=>`<option value="${n}">${i} ${n}</option>`).join('');
 $('commitmentPayment').innerHTML=PAYMENTS.map(x=>`<option value="${x}">${x}</option>`).join('');
}
function selectCategory(v){$('categoryInput').value=v;document.querySelectorAll('.category-choice').forEach(b=>b.classList.toggle('selected',b.dataset.cat===v))}
function selectPayment(v){$('paymentInput').value=v;document.querySelectorAll('.payment-choice').forEach(b=>b.classList.toggle('selected',b.dataset.pay===v))}
document.addEventListener('click',e=>{const c=e.target.closest('[data-cat]');if(c)selectCategory(c.dataset.cat);const p=e.target.closest('[data-pay]');if(p)selectPayment(p.dataset.pay);const qc=e.target.closest('[data-qcat]');if(qc){quickCategory=qc.dataset.qcat;document.querySelectorAll('.quick-cat').forEach(b=>b.classList.toggle('selected',b.dataset.qcat===quickCategory));updateQuickHint()}});
function updateQuickHint(){const amount=Number($('quickAmount').value)||0;$('quickHint').textContent=amount&&quickCategory?`Listo: ${money(amount)} en ${quickCategory}. Toca Guardar.`:'Ingresa un monto y selecciona una categoría.';$('quickHint').classList.toggle('ok',!!(amount&&quickCategory))}
$('quickAmount').addEventListener('input',updateQuickHint);
$('quickSaveBtn').onclick=()=>{const amount=Number($('quickAmount').value);if(!amount){$('quickAmount').focus();toast('Ingresa un monto');return}if(!quickCategory){toast('Selecciona una categoría');return}expenses.push({id:crypto.randomUUID(),amount,category:quickCategory,payment:'💵 Efectivo',description:'',date:today(),createdAt:Date.now()});save();$('quickAmount').value='';quickCategory='';document.querySelectorAll('.quick-cat').forEach(b=>b.classList.remove('selected'));updateQuickHint();render();toast('✓ Gasto registrado')};
function totals(){const m=expenses.filter(e=>monthKey(e.date)===currentMonth()),normal=m.reduce((s,e)=>s+e.amount,0),fixedAndInstallments=commitmentTotal(),committed=normal+fixedAndInstallments,tt=m.filter(e=>e.date===today()).reduce((s,e)=>s+e.amount,0),r=Math.max(0,(settings.budget||0)-committed);$('monthTotal').textContent=money(committed);$('todayTotal').textContent=money(tt);$('budgetTotal').textContent=money(settings.budget);$('remainingTotal').textContent=money(r);$('monthLabel').textContent=dateObj(currentMonth()+'-01').toLocaleDateString('es-CL',{month:'long',year:'numeric'})}
function item(e){return `<article class="expense-item"><div class="expense-icon">${catIcon(e.category)}</div><div class="expense-info"><strong>${esc(e.description||e.category)}</strong><small>${e.category} · ${e.payment.replace(/^[^ ]+ /,'')} · ${e.date}</small></div><div class="expense-amount">${money(e.amount)}</div><div class="item-actions"><button onclick="editExpense('${e.id}')">✏️</button><button onclick="deleteExpense('${e.id}')">🗑️</button></div></article>`}
function catData(list){const m={};list.forEach(e=>m[e.category]=(m[e.category]||0)+e.amount);const rows=Object.entries(m).sort((a,b)=>b[1]-a[1]),max=rows[0]?.[1]||1;return rows.map(([c,t])=>`<div class="cat-row"><div class="cat-top"><span>${catIcon(c)} ${c}</span><strong>${money(t)}</strong></div><div class="bar"><i style="width:${t/max*100}%"></i></div></div>`).join('')}
function commitmentCard(c,month=currentMonth()){const value=commitmentForMonth(c,month),info=c.type==='installment'?installmentInfo(c,month):null;let meta=c.type==='fixed'?`${money(value)} cada mes · Día ${c.dueDay||'—'}`:`${money(value)} este mes · ${commitmentLabel(c,month)} · Restan ${info.remaining} cuotas`;let progress=info?`<div class="cc-progress"><i style="width:${Math.min(100,info.current/info.total*100)}%"></i></div>`:'';return `<article class="commitment-card"><div class="cc-main"><div class="cc-title">${c.type==='fixed'?'🔄':'💳'} ${esc(c.name)}</div><div class="cc-meta">${esc(c.category)} · ${esc(c.payment)} · ${meta}</div><span class="cc-badge">${c.type==='fixed'?'Activo mensual':`Cuota ${info.current} de ${info.total}`}</span>${progress}</div><div class="cc-amount">${money(value)}</div><div class="cc-actions"><button onclick="showCommitmentDetail('${c.id}')">Ver detalle</button><button onclick="editCommitment('${c.id}')">✏️ Editar</button><button onclick="pauseCommitment('${c.id}')">⏸️ Pausar</button><button class="danger" onclick="cancelCommitment('${c.id}')">Cancelar</button></div></article>`}
function commitmentSummary(){const a=activeCommitments();$('commitmentSummary').innerHTML=a.length?a.slice(0,3).map(commitmentCard).join(''):`<div class="empty">No tienes compromisos activos. Agrega tus gastos fijos o compras en cuotas.</div>`}
function renderCommitments(){const active=activeCommitments(currentMonth());$('activeCommitments').innerHTML=active.length?`<div class="commitment-list">${active.map(c=>commitmentCard(c,currentMonth())).join('')}</div>`:'<div class="empty small">No tienes compromisos activos para este mes.</div>';const paused=commitments.filter(c=>c.status==='paused').sort((a,b)=>(b.updatedAt||b.createdAt)-(a.updatedAt||a.createdAt));$('pausedCommitments').innerHTML=paused.length?`<div class="commitment-list">${paused.map(c=>pausedCard(c)).join('')}</div>`:'<div class="empty small">No tienes compromisos pausados.</div>';let hist=commitments.filter(c=>c.status==='cancelled'||(c.type==='installment'&&installmentInfo(c,currentMonth()).completed)).sort((a,b)=>(b.updatedAt||b.createdAt)-(a.updatedAt||a.createdAt));$('commitmentHistory').innerHTML=hist.length?`<div class="commitment-list">${hist.map(historyCard).join('')}</div>`:'<div class="empty small">Aquí aparecerán los compromisos finalizados o cancelados.</div>'}
function pausedCard(c){return `<article class="history-card"><h3>${c.type==='fixed'?'🔄':'💳'} ${esc(c.name)}</h3><p>${c.type==='installment'?`${money(c.amount)} · ${c.totalInstallments} cuotas · Inicio ${c.startDate}`:`${money(c.amount)} al mes · Inicio ${c.startDate}`}</p><p><span class="history-status status-paused">Pausado</span></p><div class="cc-actions"><button onclick="showCommitmentDetail('${c.id}')">Ver detalle</button><button onclick="resumeCommitment('${c.id}')">▶️ Reactivar</button><button class="danger" onclick="cancelCommitment('${c.id}')">Cancelar</button></div></article>`}
function historyCard(c){let status=commitmentState(c,currentMonth()),label=status==='completed'?'Finalizado':status==='cancelled'?'Cancelado':'Pausado';let detail=c.type==='installment'?`${money(c.amount)} · ${c.totalInstallments} cuotas · Inicio ${c.startDate}`:`${money(c.amount)} al mes · Inicio ${c.startDate}`;return `<article class="history-card"><h3>${c.type==='fixed'?'🔄':'💳'} ${esc(c.name)}</h3><p>${detail}</p><p><span class="history-status ${status==='completed'?'status-completed':status==='cancelled'?'status-cancelled':'status-paused'}">${label}</span></p><div class="cc-actions"><button onclick="showCommitmentDetail('${c.id}')">Ver detalle</button></div></article>`}
function render(){totals();const m=expenses.filter(e=>monthKey(e.date)===currentMonth()).sort((a,b)=>b.createdAt-a.createdAt);$('recentList').innerHTML=m.length?m.slice(0,6).map(item).join(''):'<div class="empty">Todavía no tienes gastos registrados este mes.</div>';commitmentSummary();renderHistory();renderCommitments();const total=m.reduce((s,e)=>s+e.amount,0);$('statCount').textContent=m.length;$('statAverage').textContent=money(m.length?total/m.length:0);$('statMax').textContent=money(Math.max(0,...m.map(e=>e.amount)));$('statDays').textContent=new Set(m.map(e=>e.date)).size;$('statsCategories').innerHTML=catData(m)||'<div class="empty">Registra gastos para ver estadísticas.</div>'}
function renderHistory(){const q=$('searchInput').value.toLowerCase().trim(),c=$('categoryFilter').value,d=$('dateFilter').value,l=expenses.filter(e=>(!q||`${e.description} ${e.category} ${e.payment}`.toLowerCase().includes(q))&&(!c||e.category===c)&&(!d||e.date===d)).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt);$('historyList').innerHTML=l.length?l.map(item).join(''):'<div class="empty">No hay gastos que coincidan con los filtros.</div>'}
function openModal(id=null,preset=null){$('expenseForm').reset();$('expenseId').value=id||'';$('modalTitle').textContent=id?'Editar gasto':'Registrar gasto';selectCategory('');selectPayment('');$('dateInput').value=today();if(id){const e=expenses.find(x=>x.id===id);if(e){$('amountInput').value=e.amount;selectCategory(e.category);selectPayment(e.payment);$('descriptionInput').value=e.description||'';$('dateInput').value=e.date}}else if(preset)$('amountInput').value=preset;$('expenseModal').classList.remove('hidden');setTimeout(()=>$('amountInput').focus(),80)}
function closeModal(){$('expenseModal').classList.add('hidden')}
window.editExpense=id=>openModal(id);window.deleteExpense=id=>{if(confirm('¿Eliminar este gasto?')){expenses=expenses.filter(e=>e.id!==id);save();render();toast('Gasto eliminado')}};
$('expenseForm').onsubmit=e=>{e.preventDefault();if(!$('categoryInput').value||!$('paymentInput').value){toast('Selecciona categoría y medio de pago');return}const id=$('expenseId').value,d={amount:Number($('amountInput').value),category:$('categoryInput').value,payment:$('paymentInput').value,description:$('descriptionInput').value.trim(),date:$('dateInput').value};if(id){const i=expenses.findIndex(x=>x.id===id);expenses[i]={...expenses[i],...d}}else expenses.push({id:crypto.randomUUID(),...d,createdAt:Date.now()});save();closeModal();render();toast('✓ Gasto guardado')};
document.querySelectorAll('[data-amount]').forEach(b=>b.onclick=()=>{$('amountInput').value=b.dataset.amount});document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{showView('dashboard');$('quickAmount').value=b.dataset.quick;updateQuickHint();$('quickAmount').focus()});$('quickAddBtn').onclick=()=>openModal();$('closeModal').onclick=closeModal;$('expenseModal').onclick=e=>{if(e.target===$('expenseModal'))closeModal()};
function showView(n){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(`${n}View`).classList.add('active');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===n));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('settingsBtn').onclick=()=>showView('settings');['searchInput','categoryFilter','dateFilter'].forEach(id=>$(id).addEventListener('input',renderHistory));$('clearFilters').onclick=()=>{$('searchInput').value='';$('categoryFilter').value='';$('dateFilter').value='';renderHistory()};
$('saveBudgetBtn').onclick=()=>{settings.budget=Number($('budgetInput').value)||0;saveSettings();render();toast('✓ Presupuesto guardado')};
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({expenses,settings,commitments,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mis-gastos-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!Array.isArray(d.expenses))throw 0;if(confirm('Esto reemplazará los datos actuales. ¿Continuar?')){expenses=d.expenses;settings=d.settings||settings;commitments=Array.isArray(d.commitments)?d.commitments:commitments;save();saveSettings();saveCommitments();render();toast('✓ Datos importados')}}catch{toast('Archivo no válido')}e.target.value=''};
$('deleteAllBtn').onclick=()=>{if((expenses.length||commitments.length)&&confirm('¿Eliminar TODOS los gastos y compromisos?')){expenses=[];commitments=[];save();saveCommitments();render();toast('Datos eliminados')}};
function toggleCommitmentFields(){const type=$('commitmentType').value;$('installmentFields').classList.toggle('hidden',type!=='installment');$('fixedFields').classList.toggle('hidden',type!=='fixed')}
function openCommitmentModal(id=null){$('commitmentForm').reset();$('commitmentId').value=id||'';$('commitmentModalTitle').textContent=id?'Editar compromiso':'Agregar compromiso';$('commitmentType').value='fixed';$('commitmentDueDay').value=10;$('fixedStartDate').value=today();$('startDate').value=today();toggleCommitmentFields();if(id){const c=commitments.find(x=>x.id===id);if(c){$('commitmentType').value=c.type;$('commitmentName').value=c.name;$('commitmentAmount').value=c.amount;$('commitmentCategory').value=c.category;$('commitmentPayment').value=c.payment;$('commitmentDueDay').value=c.dueDay||10;$('fixedStartDate').value=c.startDate;$('startDate').value=c.startDate;$('totalInstallments').value=c.totalInstallments||12;toggleCommitmentFields()}}$('commitmentModal').classList.remove('hidden')}
function closeCommitmentModal(){$('commitmentModal').classList.add('hidden')}
$('commitmentType').onchange=toggleCommitmentFields;$('newCommitmentBtn').onclick=()=>openCommitmentModal();$('closeCommitmentModal').onclick=closeCommitmentModal;$('commitmentModal').onclick=e=>{if(e.target===$('commitmentModal'))closeCommitmentModal()};
$('commitmentForm').onsubmit=e=>{e.preventDefault();const id=$('commitmentId').value,type=$('commitmentType').value,name=$('commitmentName').value.trim(),amount=Number($('commitmentAmount').value),category=$('commitmentCategory').value,payment=$('commitmentPayment').value,dueDay=Math.min(31,Math.max(1,Number($('commitmentDueDay').value)||1)),startDate=type==='fixed'?$('fixedStartDate').value:$('startDate').value;if(!name||!amount||!startDate){toast('Completa los datos del compromiso');return}const d={type,name,amount,category,payment,dueDay,startDate,status:'active',updatedAt:Date.now()};if(type==='installment')d.totalInstallments=Math.max(1,Number($('totalInstallments').value)||1);if(id){const i=commitments.findIndex(x=>x.id===id);commitments[i]={...commitments[i],...d}}else commitments.push({id:crypto.randomUUID(),...d,createdAt:Date.now()});saveCommitments();closeCommitmentModal();render();toast('✓ Compromiso guardado')};
window.editCommitment=id=>openCommitmentModal(id);window.pauseCommitment=id=>{const c=commitments.find(x=>x.id===id);if(c&&confirm(`¿Pausar “${c.name}”? Dejará de descontar del presupuesto hasta reactivarlo.`)){c.status='paused';c.pausedAt=selectedPeriod;c.updatedAt=Date.now();saveCommitments();render();toast('Compromiso pausado')}};window.resumeCommitment=id=>{const c=commitments.find(x=>x.id===id);if(c&&confirm(`¿Reactivar “${c.name}”?`)){if(c.type==='installment'&&c.pausedAt){c.pausedMonths=(Number(c.pausedMonths)||0)+Math.max(0,monthDiff(dateObj(c.pausedAt+'-01'),dateObj(selectedPeriod+'-01')));}delete c.pausedAt;c.status='active';c.updatedAt=Date.now();saveCommitments();render();toast('Compromiso reactivado')}};window.cancelCommitment=id=>{const c=commitments.find(x=>x.id===id);if(c&&confirm(`¿Cancelar “${c.name}”? Pasará al historial y dejará de descontar del presupuesto.`)){c.status='cancelled';c.updatedAt=Date.now();saveCommitments();render();toast('Compromiso cancelado')}};
function showCommitmentDetail(id){const c=commitments.find(x=>x.id===id);if(!c)return;const info=c.type==='installment'?installmentInfo(c,currentMonth()):null;$('detailTitle').textContent=c.name;$('commitmentDetail').innerHTML=`<div class="commit-detail"><div class="detail-grid"><div class="detail-box"><span>Tipo</span><strong>${c.type==='fixed'?'Gasto fijo mensual':'Compra en cuotas'}</strong></div><div class="detail-box"><span>Estado</span><strong>${commitmentState(c)==='completed'?'Finalizado':commitmentState(c)==='cancelled'?'Cancelado':commitmentState(c)==='paused'?'Pausado':'Activo'}</strong></div><div class="detail-box"><span>${c.type==='fixed'?'Monto mensual':'Valor de cuota'}</span><strong>${money(c.amount)}</strong></div><div class="detail-box"><span>Categoría</span><strong>${catIcon(c.category)} ${esc(c.category)}</strong></div>${info?`<div class="detail-box"><span>Progreso</span><strong>${Math.min(Math.max(info.current,1),info.total)} de ${info.total}</strong></div><div class="detail-box"><span>Cuotas restantes</span><strong>${info.remaining}</strong></div>`:`<div class="detail-box"><span>Vencimiento</span><strong>Día ${c.dueDay}</strong></div>`}<div class="detail-box"><span>Medio de pago</span><strong>${esc(c.payment)}</strong></div><div class="detail-box"><span>Inicio</span><strong>${c.startDate}</strong></div></div>${info?`<p class="muted">${info.completed?'Este compromiso terminó y ya no descuenta del presupuesto. Permanece en el historial.':`Este mes descuenta ${money(c.amount)} del presupuesto. Al finalizar la cuota ${info.total}, desaparecerá automáticamente de los compromisos activos y pasará al historial.`}</p>`:`<p class="muted">Este gasto se descuenta del presupuesto todos los meses mientras permanezca activo.</p>`}<div class="detail-actions">${commitmentState(c,currentMonth())==='active'?`<button class="secondary-btn" onclick="editCommitment('${c.id}');closeDetailModal()">✏️ Editar</button><button class="secondary-btn" onclick="pauseCommitment('${c.id}');closeDetailModal()">⏸️ Pausar</button><button class="danger-btn" onclick="cancelCommitment('${c.id}');closeDetailModal()">Cancelar compromiso</button>`:commitmentState(c,currentMonth())==='paused'?`<button class="secondary-btn" onclick="resumeCommitment('${c.id}');closeDetailModal()">▶️ Reactivar</button><button class="danger-btn" onclick="cancelCommitment('${c.id}');closeDetailModal()">Cancelar compromiso</button>`:''}</div></div>`;$('commitmentDetailModal').classList.remove('hidden')}
window.showCommitmentDetail=showCommitmentDetail;function closeDetailModal(){$('commitmentDetailModal').classList.add('hidden')}$('closeDetailModal').onclick=closeDetailModal;$('commitmentDetailModal').onclick=e=>{if(e.target===$('commitmentDetailModal'))closeDetailModal()};
document.querySelectorAll('[data-commit-tab]').forEach(b=>b.onclick=()=>{commitmentTab=b.dataset.commitTab;document.querySelectorAll('[data-commit-tab]').forEach(x=>x.classList.toggle('active',x===b));$('activeCommitments').classList.toggle('hidden',commitmentTab!=='active');$('pausedCommitments').classList.toggle('hidden',commitmentTab!=='paused');$('commitmentHistory').classList.toggle('hidden',commitmentTab!=='history')});
setupRegisterType();document.addEventListener('misgastos:periodchange',e=>{selectedPeriod=e.detail.period;localStorage.setItem('mis_gastos_v51_selected_period',selectedPeriod);render();});
function setupRegisterType(){const normal=$('registerNormalBtn'),fixed=$('registerFixedBtn'),inst=$('registerInstallmentBtn');if(!normal)return;const buttons=[normal,fixed,inst];const activate=b=>buttons.forEach(x=>x.classList.toggle('active',x===b));normal.onclick=()=>{activate(normal);$('modalTitle').textContent='Registrar gasto';};fixed.onclick=()=>{closeModal();openCommitmentModal();$('commitmentType').value='fixed';toggleCommitmentFields();};inst.onclick=()=>{closeModal();openCommitmentModal();$('commitmentType').value='installment';toggleCommitmentFields();};}
populate();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
